// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/rightProps/components/base.vue')['default']
    CardBox: typeof import('./src/components/CardBox/index.vue')['default']
    Center: typeof import('./src/components/center/index.vue')['default']
    CompBox: typeof import('./src/components/CompBox/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./src/components/header/index.vue')['default']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    LeftCompent: typeof import('./src/components/leftCompent/index.vue')['default']
    PropsBox: typeof import('./src/components/rightProps/components/PropsBox.vue')['default']
    RightProps: typeof import('./src/components/rightProps/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
